package yjs

import (
	"bytes"
	"encoding/base64"
	"os"
	"strings"
	"testing"

	"backend/internal/domain/documentbody"

	"github.com/google/uuid"
	"github.com/reearth/ygo/crdt"
)

func TestMergeV1AppliesAndRetriesBrowserYjsUpdateIdempotently(t *testing.T) {
	// Generated by the JavaScript Yjs package with a synthetic ProseMirror
	// Y.XmlFragment document; update contains only the insertion " beta".
	base := decodeFixture(t, "AQTv5YIpAAcBC3Byb3NlbWlycm9yAwlwYXJhZ3JhcGgHAO/lgikABgQA7+WCKQEFYWxwaGEoAO/lgikABm5vZGVJZAF3EHN5bnRoZXRpYy1ub2RlLTEA")
	update := decodeFixture(t, "AQHv5YIpCITv5YIpBgUgYmV0YQA=")

	merged, err := MergeV1(base, update)
	if err != nil {
		t.Fatalf("merge browser update: %v", err)
	}

	doc := crdt.New()
	if err := crdt.ApplyUpdateV1(doc, merged, nil); err != nil {
		t.Fatalf("load merged state: %v", err)
	}
	if got, want := doc.GetXmlFragment("prosemirror").ToXML(), `<paragraph nodeId="synthetic-node-1">alpha beta</paragraph>`; got != want {
		t.Fatalf("merged XML = %q, want %q", got, want)
	}

	retried, err := MergeV1(merged, update)
	if err != nil {
		t.Fatalf("retry browser update: %v", err)
	}
	if !bytes.Equal(merged, retried) {
		t.Fatal("retry changed the encoded durable Yjs state")
	}
	retryDoc := crdt.New()
	if err := crdt.ApplyUpdateV1(retryDoc, retried, nil); err != nil {
		t.Fatalf("load retried state: %v", err)
	}
	if got, want := retryDoc.GetXmlFragment("prosemirror").ToXML(), `<paragraph nodeId="synthetic-node-1">alpha beta</paragraph>`; got != want {
		t.Fatalf("retried XML = %q, want %q", got, want)
	}
}

func TestMergeV1RejectsMalformedIncomingUpdate(t *testing.T) {
	_, err := MergeV1(nil, []byte{0xff})
	if err == nil {
		t.Fatal("expected malformed update to be rejected")
	}
}

func decodeFixture(t *testing.T, value string) []byte {
	t.Helper()
	decoded, err := base64.StdEncoding.DecodeString(value)
	if err != nil {
		t.Fatalf("decode Yjs fixture: %v", err)
	}
	return decoded
}

func TestMergeAndProjectV1MatchesMergeThenProject(t *testing.T) {
	fixture, err := os.ReadFile("testdata/full_body_v1.b64")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	state, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(fixture)))
	if err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	documentID := uuid.New()
	client := crdt.New()
	defer client.Destroy()
	if err := crdt.ApplyUpdateV1(client, state, nil); err != nil {
		t.Fatal(err)
	}
	vector, err := crdt.DecodeStateVectorV1(crdt.EncodeStateVectorV1(client))
	if err != nil {
		t.Fatal(err)
	}
	root := client.GetXmlFragment("body").Children()[0].(*crdt.YXmlElement)
	text := root.Children()[1].(*crdt.YXmlElement).Children()[0].(*crdt.YXmlText)
	if err := client.TransactE(func(tx *crdt.Transaction) error { text.Insert(tx, text.Len(), "!", nil); return nil }); err != nil {
		t.Fatal(err)
	}
	update := crdt.EncodeStateAsUpdateV1(client, vector)

	merged, body, err := MergeAndProjectV1(state, update, documentID)
	if err != nil {
		t.Fatalf("MergeAndProjectV1(): %v", err)
	}
	wantMerged, err := MergeV1(state, update)
	if err != nil {
		t.Fatal(err)
	}
	wantBody, err := ProjectV1(wantMerged, documentID)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(merged, wantMerged) {
		t.Fatal("merged state differs from MergeV1")
	}
	if !documentbody.SameContent(body, wantBody) {
		t.Fatal("projection differs from ProjectV1 of the merged state")
	}
}
