#!/usr/bin/env python3
"""Writes the catalog seed migration from docs/plans/architecture-catalog.md.

The tables under "## Hosts", "## Systems" and "## Connections (protocols)" are
the source; run this after changing them and commit the migration it writes:

    python3 scripts/catalog-seed.py backend/database/migrations/<version>_seed_catalog_entries

Entries are upserted, so a renamed entry keeps its slug and a removed row is
left in the table (mark it deprecated in the document instead of deleting it).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'docs/plans/architecture-catalog.md'


def entries(text):
    section = subkind = family = None
    order = 0
    for line in text.splitlines():
        if line.startswith('## '):
            section = line[3:].strip()
            subkind = family = None
        m = re.match(r'### Subkind `([^`]+)`', line)
        if m:
            subkind, order = m.group(1), 0
        m = re.match(r'### Family `([^`]+)`', line)
        if m:
            family, order = m.group(1), 0
        m = re.match(r'\| `([a-z0-9-]+)` \| ([^|]+)\|', line)
        if not m:
            continue
        slug, name = m.group(1), m.group(2).strip()
        order += 1
        if section == 'Hosts':
            yield slug, 'host', subkind, name, None, order
        elif section == 'Systems':
            yield slug, 'system', subkind, name, None, order
        elif section and section.startswith('Connections') and family:
            # The line-style table above the families lists families, not protocols.
            yield slug, 'protocol', family, name, family, order


def sql_text(value):
    return 'NULL' if value is None else "'" + value.replace("'", "''") + "'"


def main(prefix):
    rows = list(entries(SOURCE.read_text()))
    slugs = [r[0] for r in rows]
    if len(slugs) != len(set(slugs)):
        sys.exit('duplicate slugs in the catalog document')
    values = ',\n'.join(
        f"    ({sql_text(s)}, '{c}', {sql_text(k)}, {sql_text(n)}, {sql_text(f)}, {o})" for s, c, k, n, f, o in rows
    )
    up = (
        '-- Generated by scripts/catalog-seed.py from docs/plans/architecture-catalog.md. Do not edit by hand.\n'
        'INSERT INTO catalog_entries (slug, category, subkind, name, family, sort_order) VALUES\n'
        + values
        + '\nON CONFLICT (slug) DO UPDATE SET category = EXCLUDED.category, subkind = EXCLUDED.subkind,\n'
        '    name = EXCLUDED.name, family = EXCLUDED.family, sort_order = EXCLUDED.sort_order, deprecated = FALSE;\n'
    )
    down = '-- Generated by scripts/catalog-seed.py.\nDELETE FROM catalog_entries WHERE slug IN (' + ', '.join(sql_text(s) for s in slugs) + ');\n'
    Path(prefix + '.up.sql').write_text(up)
    Path(prefix + '.down.sql').write_text(down)
    print(f'{len(rows)} entries')


if __name__ == '__main__':
    main(sys.argv[1])
